---
abstract: "curry your \"has\"es"
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Attributes-Curried
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.84
  Sub::Exporter: 0.01
resources:
  homepage: http://github.com/sartak/moosex-attributes-curried/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/moosex-attributes-curried.git
version: 0.03
